const express = require('express');
const fetch = require('node-fetch');

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const PORT = process.env.PORT || 3001;

const app = express();
app.use(express.json({ limit: '2mb' }));

app.use((req, res, next) => {
  const origin = req.headers.origin || '';
  const allowed = [
    'https://trycueai.netlify.app',
    'https://chegv.github.io',
    'http://localhost:3000',
    'http://localhost:8080',
  ];
  if (allowed.includes(origin) || origin.startsWith('http://localhost')) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

app.get('/health', (req, res) => res.json({ status: 'ok', service: 'cue-proxy' }));

app.post('/generate-report', async (req, res) => {
  try {
    const { clientName, session, additionalContext } = req.body;

    const name       = clientName || 'Client';
    const date       = session?.date         || 'Not specified';
    const goal       = session?.goal         || 'Not specified';
    const activity   = session?.activity     || 'Not specified';
    const attempts   = session?.totalTrials       || 0;
    const independent = session?.independentTrials || 0;
    const prompted   = session?.promptedTrials    || 0;
    const goalMet    = session?.goalMet      || 'Not specified';

    const totalTrials  = parseInt(attempts)   || 0;
    const indepTrials  = parseInt(independent) || 0;
    const promptTrials = parseInt(prompted)   || 0;
    const indepPct     = totalTrials > 0 ? Math.round((indepTrials  / totalTrials) * 100) : 0;
    const promptPct    = totalTrials > 0 ? Math.round((promptTrials / totalTrials) * 100) : 0;
    const affect     = session?.affect       || 'Not specified';
    const notes      = session?.notes        || 'None';

    const prompt = `You are Cue, a clinical AI assistant for RCI-certified Speech-Language Pathologists in India. Generate a professional two-page clinical report from the session data below.

CLIENT: ${name}
DATE: ${date}
GOAL: ${goal}
ACTIVITY: ${activity}
TOTAL TRIALS: ${attempts}
INDEPENDENT RESPONSES: ${independent}
PROMPTED RESPONSES: ${prompted}
GOAL MET: ${goalMet}
AFFECT/REGULATION: ${affect}
NEXT SESSION FOCUS: ${notes}

Generate the report in this exact format with these exact headers. Use plain text only — no asterisks, no hashtags, no markdown.

PAGE 1 — CLINICAL SESSION NOTE

Client Name: ${name}
Date of Service: ${date}
Service Type: Individual Speech-Language Therapy
Clinician: RCI-Certified Speech-Language Pathologist

SUBJECTIVE:
[Client's presentation, affect, regulation, and behavioral observations during the session. Include any caregiver-reported information if available.]

OBJECTIVE:
Target Goal: ${goal}
Activity: ${activity}
Trial Data:
- Total Trials: ${totalTrials}
- Independent Responses: ${indepTrials} (${indepPct}%)
- Prompted Responses: ${promptTrials} (${promptPct}%)
- Goal Met: ${goalMet}
Client Affect/Regulation: ${affect}

ASSESSMENT:
[Clinical interpretation of performance. Comment on skill acquisition, generalization potential, impact of regulation on learning, and progress toward goals.]

PLAN:
[Next session targets, therapy modifications, strategies to support regulation, frequency recommendations.]

Next Session Focus: ${notes}

---

PAGE 2 — PARENT COMMUNICATION SUMMARY

Dear Parent/Caregiver,

Here is a summary of today's session for ${name}:

WHAT WE WORKED ON TODAY:
[Explain the goal and activity in simple, jargon-free language a non-clinician parent can understand.]

HOW ${name.toUpperCase()} DID TODAY:
[Strengths-based, positive description of the child's performance. Mention specific achievements. Frame challenges constructively.]

TRY THIS AT HOME:
1. [Practical home activity related to today's goal — specific and doable in 5 minutes]
2. [Second home activity — playful and easy to implement]
3. [Third suggestion — can be incorporated into daily routine]

COMING UP NEXT SESSION:
[Brief, encouraging preview of what will be worked on next. Keep it positive and forward-looking.]

Remember: Every session builds on the last. Your involvement at home makes a significant difference in your child's progress.

---
Generated by Cue AI | RCI-Certified SLP Documentation`;

    const upstream = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-opus-4-5',
        max_tokens: 2048,
        messages: [{ role: 'user', content: prompt }]
      }),
    });
    const data = await upstream.json();
    res.status(upstream.status).json(data);
  } catch (err) {
    console.error('Proxy error:', err);
    res.status(502).json({ error: { message: `Proxy error: ${err.message}` } });
  }
});

app.listen(PORT, () => {
  console.log(`Cue proxy listening on port ${PORT}`);
});
